name: Release

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1 

      - name: Setup Node.js              
        uses: actions/setup-node@v4.9.1 
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
                  
      - name: Install dependencies
        run: npm ci
            
      - name: Run audit
        run: npm audit signatures

      - name: Attempt to fix vulnerabilities
        run: npm audit fix

      - name: Run build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
        run: npx semantic-release
